<?php

namespace Petrae\FichierPlanteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanteRepository extends EntityRepository
{
}
