<?php

namespace Petrae\FichierPlanteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FichierPlanteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Petrae\FichierPlanteBundle\Controller\FichierPlanteController();
        return $instance;
    }
}
